//
//iSecureOS-Defaulting.m
//iSecureOS
//
//Created by GeoSn0w on 3/22/21.
// The defaulting list is used in case something bad happens and the online signatures cannot be downloaded.
// This is so that the app can also work offline.
//

#import <Foundation/Foundation.h>

NSString *iSecureOSDefaultingRepos = @"cydia.kiiimo.org,repo.hackyouriphone.org,julio.hackyouriphone.org,mainrepo.org,repo.biteyourapple.net,cydia.iphonecake.com,rejail.ru,pulandres.rejail.ru/,repo.pulandres.me,pulandres.me/repo,repo.xarold.com/,repo.xarold.com,cydia.xarold.com,julio.xarold.com,repo.insanelyi.com,repo.ipodhacks142.com,mohadu31.com,kiengk0eng.github.io,repo.cokernutx.com,2escustomservices.com/,2escustomservices.com,repo.saunderstech.co,notmytweaks.github.io,popcorntimetv.github.io,repo.kurdios.com,arab-cydia.com/repo,arab-crack.com,crack-arab.com/cydia,globalplusplus.github.io,paxcex.github.io,repo.kenhtao.net,apt.hackcn.net/,apt.hackcn.net,repo.danielpitra.cz,mrmadjb.github.io,entityz.github.io,abdomuftah.github.io,page.cocotweaks.net,repohack.github.io/mainrepo,cydia-jailbreak.github.io,cydia.popcorn-time.to,cydia.getpopcorntime.is,bo7ios.github.io/ar,cadegosser.github.io,bannerbomb.github.io/repo,repo.vip,cydia.hackulo.us,appaddict.org,appaddict.com,applecraxkhead.github.io,repo.lifpa.com,lifpa.com/repo,chase-lebo.github.io,thenightmancodeth.github.io/repo,everyonesrepo.github.io,nopiracyman.github.io,anwarvip.github.io/3rab,x7rb.gitub.io,hmodeis.firepo.me,chasewyrick.github.io,s3ud-alshaman.github.io/cydia,apt.sunbelife.com,repo.gclouds.info/,repo.gclouds.info,xlsn0w.github.io/tweak,xlsn0w.github.io/ipas,cydia.vacation-et.work/private,cydia.vacation-et.work,repo.hex-lab.com,apt.cydia.tw,system.in-appstore.com/repo,mokadam.xrepo.co,cydiadump.github.io,cydia.popcorn-time.se,cydia.popcorn-time.ch,sevenpastzeero.github.io,anvem.top/,anvem.top,guofenpai.github.io/repo/,guofenpai.github.io/repo,itweaks.net,pwnders.github.io/repo,pwnders.github.io,iter99.github.io/repo,repo.dpkghub.com,juliovern.github.io,muscledspider77.github.io/Repo,assenssion.me,mrmadtw.github.io/repo,apt.abcydia.com,iosn3rd.yourepo.com,iostonykraft.github.io,jailbreakvideo.ru,jailbreakvideo.ru/ios,crak.cn,repo.appvv,cydia.xsellize.com,hiyph.us,ihacksrepo.com,sinfuliphonerepo.com,ihackstore.com/repo,idwaneo.org/repo,stemgrade180.yourepo.com,filippobiga.me/repo,iosgods.com/repo,cydia.heaveniphone.com,watking01.github.io/repo,repo.initnil.com,ali7assan.com,check0ver.com,EOF";
